### ISSUE TITLE
I need HELP 

### ISSUE THREAD

**Issue by AFrenchCroissant** [SteffTek/swf-dev-kit#5]
I don't understand anything about this plugin. Also, there is NO video on youtube. I think this is a good plugin but I just want to have an HTML page showing up when I go on my private IP address. I even tried the example website but it's just not loading. i just get 404 on the screen. Can you send me a quick setup tutorial please
thanks

**Comment by SteffTek** [comment]
Hey! Thanks for your Ticket.

Do you have an .html file ready? If so, place it inside the WebServer folder. In the config file, you need to adjust the default path to "/YOURFILE.html". 

The 404 Page is shown, because you dont specify any Routes with the WebBuilder and dont have a default path set in the settings to an .html file. 

Write if you need an indepth guide into webbuilders.

**Comment by AFrenchCroissant** [comment]
Yes ! it work but i can't see images

**Comment by SteffTek** [comment]
Images have to be placed in the WebServer folder too. If they are in the main directory of the folder the path to the image is simply "/FILE.PNG". If it's in a subfolder you have to specify it. The WebServer folder works like a normal WebServer would.
